name: Sendit Astro template with config

steps:
  - I run "cp -R %test_sites%/sendit-astro-template-with-config src"
  - ref: ./core/run_gadget.toolproof.yml
  - snapshot: stdout
    snapshot_content: |-
      ╎{
      ╎  "ssg": "astro",
      ╎  "config": {
      ╎    "paths": {
      ╎      "static": "public",
      ╎      "uploads": "public/uploads"
      ╎    },
      ╎    "timezone": "Pacific/Auckland",
      ╎    "markdown": {
      ╎      "engine": "commonmark",
      ╎      "options": {
      ╎        "gfm": true
      ╎      }
      ╎    }
      ╎  },
      ╎  "collections": [
      ╎    {
      ╎      "key": "source",
      ╎      "suggested": false,
      ╎      "config": {
      ╎        "path": "",
      ╎        "icon": "package_2",
      ╎        "disable_url": true
      ╎      },
      ╎      "collections": [
      ╎        {
      ╎          "key": "src",
      ╎          "suggested": false,
      ╎          "config": {
      ╎            "path": "src",
      ╎            "icon": "abc",
      ╎            "disable_url": true
      ╎          },
      ╎          "collections": [
      ╎            {
      ╎              "key": "pages_1",
      ╎              "suggested": true,
      ╎              "config": {
      ╎                "path": "src/pages",
      ╎                "icon": "pages"
      ╎              },
      ╎              "collections": []
      ╎            },
      ╎            {
      ╎              "key": "shared",
      ╎              "suggested": false,
      ╎              "config": {
      ╎                "path": "src/shared",
      ╎                "icon": "share",
      ╎                "disable_url": true
      ╎              },
      ╎              "collections": [
      ╎                {
      ╎                  "key": "shared_astro",
      ╎                  "suggested": true,
      ╎                  "config": {
      ╎                    "path": "src/shared/astro",
      ╎                    "icon": "share_eta",
      ╎                    "disable_url": true
      ╎                  },
      ╎                  "collections": []
      ╎                }
      ╎              ]
      ╎            },
      ╎            {
      ╎              "key": "content",
      ╎              "suggested": false,
      ╎              "config": {
      ╎                "path": "src/content",
      ╎                "icon": "wysiwyg"
      ╎              },
      ╎              "collections": [
      ╎                {
      ╎                  "key": "posts",
      ╎                  "suggested": true,
      ╎                  "config": {
      ╎                    "icon": "newspaper",
      ╎                    "path": "src/content/blog",
      ╎                    "url": "/blog/[slug]/",
      ╎                    "disable_add_folder": true,
      ╎                    "_enabled_editors": [
      ╎                      "content",
      ╎                      "visual"
      ╎                    ],
      ╎                    "add_options": [
      ╎                      {
      ╎                        "name": "Add New Post",
      ╎                        "schema": "default",
      ╎                        "icon": "post_add"
      ╎                      }
      ╎                    ],
      ╎                    "schemas": {
      ╎                      "default": {
      ╎                        "name": "New Post",
      ╎                        "path": ".cloudcannon/schemas/post.md"
      ╎                      }
      ╎                    },
      ╎                    "_inputs": {
      ╎                      "title": {
      ╎                        "type": "text",
      ╎                        "options": {
      ╎                          "required": true,
      ╎                          "empty_type": "string"
      ╎                        }
      ╎                      },
      ╎                      "image_alt": {
      ╎                        "type": "text",
      ╎                        "options": {
      ╎                          "empty_type": "string"
      ╎                        }
      ╎                      },
      ╎                      "author": {
      ╎                        "type": "text",
      ╎                        "options": {
      ╎                          "empty_type": "string"
      ╎                        }
      ╎                      },
      ╎                      "thumb_image.image": {
      ╎                        "type": "image",
      ╎                        "options": {
      ╎                          "required": true,
      ╎                          "width": 500,
      ╎                          "height": 413,
      ╎                          "resize_style": "crop"
      ╎                        }
      ╎                      },
      ╎                      "featured_image.image": {
      ╎                        "type": "image",
      ╎                        "comment": "The hero image used at the top of the page",
      ╎                        "options": {
      ╎                          "width": 1296,
      ╎                          "resize_style": "crop"
      ╎                        }
      ╎                      }
      ╎                    }
      ╎                  },
      ╎                  "collections": []
      ╎                },
      ╎                {
      ╎                  "key": "pages",
      ╎                  "suggested": true,
      ╎                  "config": {
      ╎                    "path": "src/content/pages",
      ╎                    "url": "/[slug]/",
      ╎                    "icon": "wysiwyg",
      ╎                    "disable_add_folder": true,
      ╎                    "_enabled_editors": [
      ╎                      "visual"
      ╎                    ],
      ╎                    "add_options": [
      ╎                      {
      ╎                        "name": "Add New Page",
      ╎                        "schema": "default",
      ╎                        "icon": "note_add"
      ╎                      }
      ╎                    ],
      ╎                    "schemas": {
      ╎                      "default": {
      ╎                        "name": "New Page",
      ╎                        "path": ".cloudcannon/schemas/page.md",
      ╎                        "new_preview_url": "/"
      ╎                      },
      ╎                      "paginated_collection": {
      ╎                        "path": ".cloudcannon/schemas/paginated-collection.md"
      ╎                      }
      ╎                    },
      ╎                    "_inputs": {
      ╎                      "content_blocks": {
      ╎                        "type": "array",
      ╎                        "options": {
      ╎                          "empty_type": "array"
      ╎                        }
      ╎                      }
      ╎                    }
      ╎                  },
      ╎                  "collections": []
      ╎                }
      ╎              ]
      ╎            }
      ╎          ]
      ╎        },
      ╎        {
      ╎          "key": "data",
      ╎          "suggested": true,
      ╎          "config": {
      ╎            "path": "data",
      ╎            "disable_add": true,
      ╎            "disable_add_folder": true,
      ╎            "disable_url": true,
      ╎            "icon": "data_usage",
      ╎            "_inputs": {
      ╎              "social": {
      ╎                "type": "array",
      ╎                "options": {
      ╎                  "structures": "_structures.social_links"
      ╎                }
      ╎              },
      ╎              "sections": {
      ╎                "type": "array",
      ╎                "options": {
      ╎                  "structures": "_structures.sections"
      ╎                }
      ╎              },
      ╎              "favicon_icon": {
      ╎                "type": "image",
      ╎                "comment": "For the shortcut icon meta tag"
      ╎              },
      ╎              "favicon_image": {
      ╎                "type": "image",
      ╎                "comment": "For the icon meta tag"
      ╎              },
      ╎              "twitter_site": {
      ╎                "type": "twitter",
      ╎                "label": "Twitter Username"
      ╎              },
      ╎              "logo_url": {
      ╎                "comment": "Link for the logo in the top left of the footer"
      ╎              },
      ╎              "copyright": {
      ╎                "comment": "Automatically prefixed with the current year"
      ╎              },
      ╎              "enable_nav_btn": {
      ╎                "type": "switch"
      ╎              },
      ╎              "nav_btn": {
      ╎                "hidden": "!enable_nav_btn",
      ╎                "options": {
      ╎                  "preview": {
      ╎                    "icon": "smart_button"
      ╎                  }
      ╎                }
      ╎              }
      ╎            }
      ╎          },
      ╎          "collections": []
      ╎        }
      ╎      ]
      ╎    }
      ╎  ]
      ╎}
