# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Feature Hero
  description: Feature Hero section
  icon: "contactless"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Run the best campaigns
  description: Sendit will change the way you think about email and marketing automation..
  btn:
    link: /#
    text: Try This Free
  image_path: /images/feature/feature-hero.png

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
  image:
    type: image
    options:
      width: 696
      height: 721
      resize_style: crop
