name: CLI generate auto with init-settings

steps:
  - I run "cp -R %test_sites%/sendit-hugo-template src"
  - ref: ../core/run_gadget_cli.toolproof.yml
  - I run "npm -s run gadget -- generate src --auto --init-settings"
  - I run "cat src/cloudcannon.config.yml"
  - stdout should contain "collections_config"
  - I run "cat src/.cloudcannon/initial-site-settings.json"
  - stdout should contain "hugo"
