name: CLI init-settings subcommand

steps:
  - I run "cp -R %test_sites%/sendit-astro-template src"
  - ref: ./core/run_gadget_cli.toolproof.yml
  - I run "npm -s run gadget -- init-settings src"
  - step: I read the file "src/.cloudcannon/initial-site-settings.json"
  - stdout should contain "$schema"
  - stdout should contain "\"ssg\": \"astro\""
  - stdout should contain "install_command"
  - stdout should contain "build_command"
  - stdout should contain "output_path"
